import Main from "@/components/Main";
import "./globals.css";
import type { Metadata } from "next";
import Aside from "@/components/Aside";

export const metadata: Metadata = {
  title: "Multi step form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="sm:flex w-full h-screen sm:items-center sm:justify-center">
        <Main>
          <Aside />
          {children}
        </Main>
      </body>
    </html>
  );
}
